"""
📁 File Structure
--J2pcm(Package)
|----__init__.py
|----cli.py
|----json_to_base_class_model.py
|----json_to_dataclass_model.py
|----json_to_nested_parallel_class.py
|----json_to_property_model.py
|----json_to_protocol_model.py
|----json_to_typed_dict_class_model.py
"""
from setuptools import setup, find_packages

setup(
    name="J2pcm",
    version="0.1.0",
    author="PythonnotJava",
    author_email="2565497078@qq.com",
    description="`J2pcm` is designed for `Json Object to Python Class Model`.The code generated by J2pcm is statically `typed` and even `type-safe`.",
    long_description=open("README.md", 'r', encoding='U8').read(),
    long_description_content_type="text/markdown",
    url="https://github.com/PythonnotJava/J2pcm",
    packages=find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Topic :: Software Development :: Code Generators",
    ],
    python_requires='>=3.12',
    entry_points={
        'console_scripts': [
            'J2pcm = J2pcm.cli:cli',
        ],
    },
)